language: node_js
node_js:
- 10
cache:
  directories:
  - node_modules
install: npm install
scripts:
- bash ./deploy/deploy.sh
sudo: false
deploy:
  provider: npm
  email: thomas@flack.it
  api_key:
    secure: THbc8Gc3Glbj78ZWq3mZHWEqCPO/2DuikM9VQcGab07X1mtSZz3YwxG+rOYVPXpv09dpUXt3lm+6WMtuDt33LLEtAykzqX9f10nz9XqqTmiy5k0nwrmM4HNGkRK6ZCpEQmteNLrtxcOZDoFjvoGtTG53T7eOiyH5JWZXwqPwtDtx0ZtjXhYxF9LnSzcUV4W3HzOu4vTTxonc/LTbNnGue4wvaJyDXYC6qOxbVzkQc3j7WjVtlGazAsZjDWZFC103YQo9eihEmaNU4hLUEqcF5VfinoO+JMp2J7SGKPLDDrJn3XU5FFIdCv497S6DUgQTzhZs/M96dHOpwvJ3vPipiQEvRxMhp/g2k6cLogpNEDNtUoIQ0Foo3Bvf2LoMokEk+YjGwm0/bQAp2qxAPMRmoohhl4UuFlvHg9ixQFrELPBNznb3mmamFfljZhbQ1L2yjUE3hH+WEzeE8RXGI103tbbX0PqjmpNXFzgGJ69k4wJdojz5jXPQILluJ/fCzDRKFIIIxAzxgM5YkUFhxdgnqffATJ8guAIXVCg0vycdXiJsHN0xINTgL2nwg1FEIn25OnpzByOK/0+Mgx6yGdRroHks5XXIVMkoqSA2o0vPKRt7kzaDleASrRpMkEUuu8Eiwyu7L6g2taYn5vZJnWBiPMz+CFJiye4uzsZ01ZHnoOE=
  on:
    tags: true
    repo: vaequitas/last-fm.js
